// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// betaf
List betaf(arma::mat& Z, arma::rowvec& f, int& k, int& sel);
RcppExport SEXP gdpc_betaf(SEXP ZSEXP, SEXP fSEXP, SEXP kSEXP, SEXP selSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< int& >::type sel(selSEXP);
    __result = Rcpp::wrap(betaf(Z, f, k, sel));
    return __result;
END_RCPP
}
// matrix_C
arma::mat matrix_C(arma::rowvec& betav, double& alfa, int& k);
RcppExport SEXP gdpc_matrix_C(SEXP betavSEXP, SEXP alfaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec& >::type betav(betavSEXP);
    Rcpp::traits::input_parameter< double& >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< int& >::type k(kSEXP);
    __result = Rcpp::wrap(matrix_C(betav, alfa, k));
    return __result;
END_RCPP
}
// matrix_D
arma::mat matrix_D(arma::rowvec& betav, int& N, int& k);
RcppExport SEXP gdpc_matrix_D(SEXP betavSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec& >::type betav(betavSEXP);
    Rcpp::traits::input_parameter< int& >::type N(NSEXP);
    Rcpp::traits::input_parameter< int& >::type k(kSEXP);
    __result = Rcpp::wrap(matrix_D(betav, N, k));
    return __result;
END_RCPP
}
// matrix_ff
arma::vec matrix_ff(arma::mat& Z, arma::mat& beta, arma::vec& alpha, int& k);
RcppExport SEXP gdpc_matrix_ff(SEXP ZSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int& >::type k(kSEXP);
    __result = Rcpp::wrap(matrix_ff(Z, beta, alpha, k));
    return __result;
END_RCPP
}
