# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

betaf <- function(Z, f, k, sel) {
    .Call('gdpc_betaf', PACKAGE = 'gdpc', Z, f, k, sel)
}

matrix_C <- function(betav, alfa, k) {
    .Call('gdpc_matrix_C', PACKAGE = 'gdpc', betav, alfa, k)
}

matrix_D <- function(betav, N, k) {
    .Call('gdpc_matrix_D', PACKAGE = 'gdpc', betav, N, k)
}

matrix_ff <- function(Z, beta, alpha, k) {
    .Call('gdpc_matrix_ff', PACKAGE = 'gdpc', Z, beta, alpha, k)
}

