# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatrixBeta <- function(Z, f, k, sel) {
    .Call('gdpc_getMatrixBeta', PACKAGE = 'gdpc', Z, f, k, sel)
}

getF <- function(Z, beta, alpha, k) {
    .Call('gdpc_getF', PACKAGE = 'gdpc', Z, beta, alpha, k)
}

getFitted <- function(f_fin, f_ini, beta, alpha, k) {
    .Call('gdpc_getFitted', PACKAGE = 'gdpc', f_fin, f_ini, beta, alpha, k)
}

getFini <- function(Z, k) {
    .Call('gdpc_getFini', PACKAGE = 'gdpc', Z, k)
}

